### ISSUE TITLE
[Bug] Losing doors parameters after map change

### ISSUE THREAD

**Issue by odessadraekavik** [Chessnut/hl2rp#1]
Hello,

Unownable doors are not saved after a map change.
##### To Reproduce :

```
> Set a door "unownable"
> Change Map / Restart Server
> Profit
```

**Comment by Chessnut** [comment]
What type of door is it? E.g. sliding, regular rotating door, etc..

**Comment by odessadraekavik** [comment]
The doors we can find on the map rp_industrial17_v1
(Normal rotating doors)
http://steamcommunity.com/sharedfiles/filedetails/?id=171962560&searchtext=industrial

**Comment by DevulOLD** [comment]
I'm having the exact same issue.

**Comment by Xenomorph-King** [comment]
Exact same here. Its annoying esepcially with City 45's hundreds of doors.

**Comment by DevulOLD** [comment]
Update: Try purchasing a door you set as unownable after a server restart; it says it is unownable, right?

**Comment by KaiNW** [comment]
same problem here.
with all doors, map city 8

**Comment by Chessnut** [comment]
I can't seem to replicate it on City 18.

**Comment by DevulOLD** [comment]
It was fixed by Rebel some time ago
