### ISSUE TITLE
[REQUEST] Add a setfaction command?

### ISSUE THREAD

**Issue by Xenomorph-King** [Chessnut/hl2rp#10]
If there isn't already, could we have a /charsetfaction <player> <faction> <class (optional)> for setting a character's faction? I hate telling someone to remove their current player and create a new Civil Protection character because there is no setfaciton.

For example: /charsetfaction Zombuck "Civil Protection" "RCT"
That would randomly generate units and use the correct model.

**Comment by KaiNW** [comment]
great idea. but if a user wanna have 2 "lives"? as Citizen and OW for example..

**Comment by Xenomorph-King** [comment]
Then an admin can set their whitelist to be that, I get the point. I mean in situations like one of my members applies for Civil Protection, and basically one of your character's ingame wants to be a Civil Protection. Hopeuflly you get my point

**Comment by Imacc2009** [comment]
It's been made into a plugin by Zenolisk
https://github.com/Chessnut/NSPlugins/blob/master/FactionTransfer.zip
