### ISSUE TITLE
T-Pose nut.anim.setModelClass wont work either, help?

### ISSUE THREAD

**Issue by ChazNN** [Chessnut/hl2rp#100]
So I figured out all my class stuff but for the life of me I cant get my models to work and they all T-Pose. Ive put

nut.anim.setModelClass("models/player/pmc_3/pmc__10.mdl", "metrocop")
nut.anim.setModelClass("models/player/pmc_3/pmc__07.mdl", "metrocop")
nut.anim.setModelClass("models/player/pmc_3/pmc__03.mdl", "metrocop")
nut.anim.setModelClass("models/player/pmc_3/pmc__01.mdl", "metrocop")

For each of the four in there for each faction and they still T-Pose. Ive tried making a plugin, putting them in my sh_schema and tried putting them in the individual faction lua's

I even tried doing it reversed with the model and animation, ive tried capitalizing and lowercasing set.

**Comment by FrostyNow** [comment]
That models are working on player animation not metrocop one.
Change “metrocop” to “player”.
