### ISSUE TITLE
CID won't assign

### ISSUE THREAD

**Issue by SgtMaster** [Chessnut/hl2rp#104]
Hey yesterday I installed NS HL2RP and I tried to use ration dispenser with my friend, when I tried to assign a CID to my friend, the CID didn't "get assigned". If someone could help me, please. Also I would like to know how to use ration dispenser. Thanks.

**Comment by russianmtf** [comment]
1. Does he already have a CID. 
2. Someone with a CID walks up to the dispenser and it drops rations.
