### ISSUE TITLE
Removing CP visor hud

### ISSUE THREAD

**Issue by LordAuld** [Chessnut/hl2rp#109]
I'm wondering if it was possible to somehow remove the ''rippling/screen'' looking visor hud you constantly have on if you're assigned to the civil protection faction?

**Comment by LordAuld** [comment]
![5132a722d497a4628870279bc711a3ce](https://cloud.githubusercontent.com/assets/22603559/19155427/d1cbfa80-8bb4-11e6-9872-307579ab53e9.png)

**Comment by DrodA** [comment]
Remove **`self.overlay`** from [here](https://github.com/Chessnut/hl2rp/blob/1.1/schema/hooks/cl_hooks.lua#L5).
