### ISSUE TITLE
im not sure what it is please reply anyone 

### ISSUE THREAD

**Issue by sky0693** [Chessnut/hl2rp#112]
it just says 
Couldn't change active gamemode - 'hl2rp-1.1' not found

please help if you need the addons here 
Collection has 12 Addons
Mounting Addon ' Enhanced Citizens V2' (114502372)
Mounting Addon 'Beta Metrocop Sounds' (175272156)
Mounting Addon 'Combine Administrators v2' (105042805)
Mounting Addon 'Combine APC' (118997241)
Mounting Addon 'Combine Officers V3' (140549363)
Mounting Addon 'Half-Life 2 Tools' (104619813)
Mounting Addon 'Medic Citizens' (130200500)
Mounting Addon 'Metropolice Pack' (104491619)
Mounting Addon 'NutScript Content' (207739713)
Mounting Addon 'Suit-Wearing Citizens ragdolls' (109062494)
Mounting Addon '[Official] Precision Tool' (104482086)
Mounting Addon 'Rp_City17 - Open Beta [Build 210]' (150899249)

nutscript any one help me

**Comment by art-gur** [comment]
Rename your folder with HL2RP gamemode to hl2rp and set in server setup parameters -gamemode hl2rp.
