### ISSUE TITLE
Couldn't change active gamemode - 'HL2RP' not found  

### ISSUE THREAD

**Issue by Kangela** [Chessnut/hl2rp#117]
I cannot run ns hl2rp server because of this error. What should I do? ("hl2rp" file name is already same with "hl2rp.txt")
I'm using this (srcds.bat)
-> srcds.exe -console -game garrysmod +map "rp_city8_2_dnaco" -maxplayers 10 +gamemode "hl2rp"

**Comment by Gardee** [comment]
Same here

**Comment by SkyArmyNinja** [comment]
Change the name of the folder in gamemodes from "hl2rp-1.1" to "hl2rp" and make sure you extracted it from the .zip file.

**Comment by rebel1324** [comment]
Please go to rebel1324/Nutscript for further support.

Windows 10용 메일에서 보냄

보낸 사람: SkyArmyNinja
보낸 날짜: 2018년 4월 5일 목요일 오후 10:32
받는 사람: Chessnut/hl2rp
참조: Subscribed
제목: Re: [Chessnut/hl2rp] Couldn't change active gamemode - 'HL2RP' notfound (#117)

Change the name of the folder in gamemodes from "hl2rp-1.1" to "hl2rp" and make sure you extracted it from the .zip file.
