### ISSUE TITLE
CP F1 Menu Broken and CP Unable to Open Doors

### ISSUE THREAD

**Issue by CarrotMist** [Chessnut/hl2rp#118]
Hey so I just installed a fresh version of NS and HL2RP but the F1 menu seems broken if you're on a CP character and CP's can't open the nexus doors even after the doors are set to be faction owned by the Civil Protection. I'm using NS 1.1 and the updated version of HL2RP for 1.1, and there are no plugins on the server.

The error I receive when on a CP pressing F1 is:
[ERROR] gamemodes/hl2rp/schema/sh_schema.lua:20: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. getCombineRank - gamemodes/hl2rp/schema/sh_schema.lua:20
    3. canBe - gamemodes/hl2rp/schema/sh_schema.lua:67
     4. fn - gamemodes/nutscript/gamemode/core/derma/cl_classes.lua:146
      5. Run - addons/ulib/lua/ulib/shared/hook.lua:110
       6. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:39
        7. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
         8. unknown - `gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:624

**Comment by HeyBanditoz** [comment]
This is not being maintained. You're better off fixing the issues yourself, or finding fixes from a downstream.

On January 7, 2018 12:36:09 AM MST, CarrotMist <notifications@github.com> wrote:
>Hey so I just installed a fresh version of NS and HL2RP but the F1 menu
>seems broken if you're on a CP character and CP's can't open the nexus
>doors even after the doors are set to be faction owned by the Civil
>Protection. I'm using NS 1.1 and the updated version of HL2RP for 1.1,
>and there are no plugins on the server.
>
>The error I receive when on a CP pressing F1 is:
>[ERROR] gamemodes/hl2rp/schema/factions/sh_metropolice.lua:13: attempt
>to compare number with nil
>  1. Run - gamemodes/hl2rp/schema/factions/sh_metropolice.lua:13
>2. onPostSetup -
>gamemodes/nutscript/gamemode/core/libs/sh_character.lua:313
>3. setUp - gamemodes/nutscript/gamemode/core/derma/cl_charcreate.lua:78
>4. callback -
>gamemodes/nutscript/gamemode/core/derma/cl_character.lua:195
>5. DoClick -
>gamemodes/nutscript/gamemode/core/derma/cl_character.lua:111
>6. unknown -
>gamemodes/nutscript/gamemode/core/derma/cl_menubutton.lua:5
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Chessnut/hl2rp/issues/118

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brianhang** [comment]
For reference, this would happen if you delete one tables for ranks here: https://github.com/Chessnut/hl2rp/blob/1.1/schema/sh_config.lua#L66
