### ISSUE TITLE
Door of the nexus don't works

### ISSUE THREAD

**Issue by Mapek123** [Chessnut/hl2rp#119]
I klick e on doors of nexus and i cant opened him help version 1.1

**Comment by HeyBanditoz** [comment]
Try again.

On January 17, 2018 5:09:38 AM MST, Mapek123 <notifications@github.com> wrote:
>I klick e on doors of nexus and i cant opened him help
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Chessnut/hl2rp/issues/119

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
