### ISSUE TITLE
Recent issues

### ISSUE THREAD

**Issue by BizLight** [Chessnut/hl2rp#121]
### **_Recent issues with nutscript and the hl2rp schema. Can you help me?_**

[NutScript] Item at 'nutscript/gamemode/items/base/sh_ammo (2).lua' follows invalid naming convention!

registerInv is deprecated
        gamemodes/nutscript/gamemode/items/base/sh_bags.lua:143: in function 'onRegistered'

[NutScript] Item at 'nutscript/gamemode/items/base/sh_outfit (2).lua' follows invalid naming convention!
[NutScript] Item at 'nutscript/gamemode/items/base/sh_pacoutfit (2).lua' follows invalid naming convention!
[NutScript] Item at 'nutscript/gamemode/items/base/sh_weapons (2).lua' follows invalid naming convention!

[็|2|STEAM_0:1:213402156] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_character.lua:36: attempt to index global 'SCHEMA' (a nil value)
  1. Init - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:36
   2. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
    3. fn - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:589
     4. Run - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
      5. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:341

[็|2|STEAM_0:1:213402156] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/items/base/sh_bags.lua:143: attempt to call field 'registerInv' (a nil value)
  1. onRegistered - gamemodes/nutscript/gamemode/items/base/sh_bags.lua:143
   2. register - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:176
    3. load - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:76
     4. loadFromDir - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:198
      5. unknown - gamemodes/nutscript/gamemode/shared.lua:59
       6. include - [C]:-1
        7. unknown - gamemodes/nutscript/gamemode/cl_init.lua:8
         8. DeriveGamemode - [C]:-1
          9. unknown - gamemodes/hl2rp/gamemode/cl_init.lua:1
### 
**_Images below for further clarification:_**
![issue1](https://user-images.githubusercontent.com/29734480/48140130-d4604300-e2b0-11e8-879d-3e3ec7af8bb4.PNG)
![issue2](https://user-images.githubusercontent.com/29734480/48140131-d4604300-e2b0-11e8-8758-48c0101f73c5.PNG)
![issue3](https://user-images.githubusercontent.com/29734480/48140132-d4604300-e2b0-11e8-83b9-2bfb7fa000ad.jpg)
![issue4](https://user-images.githubusercontent.com/29734480/48140133-d4f8d980-e2b0-11e8-9ca2-9798be0072fc.PNG)
![issue5](https://user-images.githubusercontent.com/29734480/48140135-d4f8d980-e2b0-11e8-8a61-a1b4484f6fac.PNG)

**Comment by brianhang** [comment]
To update from NS1.1 to NS2.0, you need to completely remove the nutscript folder before replacing it.
