### ISSUE TITLE
Some bugs & suggestions.

### ISSUE THREAD

**Issue by ghost** [Chessnut/hl2rp#14]
1) Character model SOMETIMES stays the same after switching to a new character. This happens to everyone on my server every now and then.

2) Prices won't stay the same after changing them on a placed vendor.

3) Some CP models will lay down further into the game when running. (_When you hold WASD the model will appear to everyone as they were laying down, but still running. However, I think this is just the resource workshop file that is added into the schema as I know of it from GMOD 12._)

4) No way to announce anything to all players. However, we've been using // for this just adding **********\* in front. (i.e ******************_Rations Disp. Open!**_*************)

5) Doors that aren't ownable, should have no text. People should be able to differentiate them.

6) Some additional functionality to the scanner would be nice, not having a radio kind of sucks, but I guess thats why /dispatch was added.

7) No way to get a new Citizen ID card if lost, vendors only sell 00000 cards. Though, I guess that adds to the roleplay. But, there's alot of scenarios where a player could lose this and it would not be their fault at all.

Me and my community are having a great time playing on this schema, so I hope you attend to some of these bugs!

Thank you!

**Comment by Imacc2009** [comment]
4) You can use /event or /dispatch (dispatch only works as an elite CP rank)
