### ISSUE TITLE
[Bug] Couldn't change active gamemode - 'HL2RP' not found

### ISSUE THREAD

**Issue by eerse** [Chessnut/hl2rp#16]
I did everything in the video but substituted with hl2rp and my console got this.

**Comment by eerse** [comment]
Fixed it,

**Comment by Kangela** [comment]
How did you fix it?

**Comment by eerse** [comment]
Sorry, I can't really remember, it's been years. If you submit a support
ticket to your server hosts, they should definitely be able to help.
