### ISSUE TITLE
[Suggestion] Commands Auto-Completion & RP Tools

### ISSUE THREAD

**Issue by odessadraekavik** [Chessnut/hl2rp#2]
Hello again,
### Auto-Completion Idea

The idea would be to implement an auto completion system for chat commands.
( Kinda like on... another roleplaying gamemode, you know what I mean. )
### RP Tools Idea

Would be to implement a set of usefull "tools" to make it easier to : 
- Tool to set doors Ownable/Unownable
- Tool to change doors Name
- Tool to add/remove Areas & 3D Texts

**Comment by franzhoog** [comment]
There are tools to do EVERYTHING you just whined about in Nutscript already. Look harder - maybe actually look at the help menu or play around with the commands.

**Comment by odessadraekavik** [comment]
Thanks for your answer, But, I was talking about "TOOLGUN" Tools, I know there are "commands" to do that, that's why I typed : 

##### [...] to make it easier to [...]

Also, "Look Harder" There is "NO" /textadd in the help menu.
( Ps : I'm not whining about Nutscript, it's an amazing framework, I mean it ! I'm just new to it and i'm trying to help by reporting issues and giving ideas. it's your choice to take theses ideas or not. not mine.)

**Comment by Chessnut** [comment]
I was actually going to make it so when registering a command, you can specify a leftClick function which would automatically register a new STool.
