### ISSUE TITLE
[MOAR SUGGESTIONS]Here could be your title.

### ISSUE THREAD

**Issue by KaiNW** [Chessnut/hl2rp#23]
And again i got ideas for da RP:

1.Still Option making Combine and doors able to open from other factions (Doorgroup)
2. Better CID: Option to set Verdict Points, Loyality Points. 
3. Remade Ration Dispenser: The Dispenser checks the CID (if ^ is implemented) for Verdict/Loyality points (and if CWU faction) and then it dispenses when the defined amout of verdict points is reached nothing, and if CWU or what else it dispenses 2.
4. News Terminal: A Terminal for Citizens where they can look for updates(news)
5. Tokens panel?

**Comment by ArttuFromHyperia** [comment]
2: /data is already there.

**Comment by KaiNW** [comment]
I mean to combine them.

**Comment by ghost** [comment]
I think the CWU thing in 3. should be optional, not everyone is going to use a CWU faction (or at least the name CWU).

**Comment by KaiNW** [comment]
As i said, could even be an other faction like Civil Gangsters Army or stuff like that. you know.
