### ISSUE TITLE
Hands not working properly?

### ISSUE THREAD

**Issue by AtomiCAST** [Chessnut/hl2rp#24]
So, the first day i downloaded the Schema and the Framework the hands were functional, nowdays they stopped working. (They're like the Buggy clockwork ones)

Is it possible to fix the hands not being showed when Raising them?

**Comment by Chessnut** [comment]
Well what are the bugs?

**Comment by AtomiCAST** [comment]
They don't show up when you raise them.

**Comment by Chessnut** [comment]
Any errors? Try restarting the server/GMod

**Comment by AtomiCAST** [comment]
Haven't seen any errors. I reinstalled a few days back my gmod server, aswell the schema. Nothing changed tho

**Comment by Chessnut** [comment]
What model are you using?

**Comment by AtomiCAST** [comment]
I just tested the Citizens one and they work, Metro Police Pack ones won't work. Is there a way to force the use of some of the default HL2 hands?

**Comment by Chessnut** [comment]
No
