### ISSUE TITLE
[Suggestion] Model head replacement

### ISSUE THREAD

**Issue by ghost** [Chessnut/hl2rp#26]
If possible, you could make it so Civil Protection characters are able to take their helmets off through a menu and have a preset citizen model for the head to be used.

Also for Administrator as there are few models for that faction, the suit in the Workshop addon looks good to be for all models headhack (except for the dark skinned individuals).

Not really that necessary for CP, as they have barely need of taking off their helmets. But a head replacement for the Administrator suits would be enough.

**Comment by Bucky21659** [comment]
AFAIK there isn't a way to do a lua-based character headhack that's built into NutScript.
I believe there's addons that'll allow this though.

**Comment by Chessnut** [comment]
Why wouldn't it be possible? Use Lua.
