### ISSUE TITLE
Vendor resets his price

### ISSUE THREAD

**Issue by Applad** [Chessnut/hl2rp#30]
I've got a problem about the vendor.

If I set the price to 0, with right-click, in the admin menu, press save, close it and open it up again the price will be the price of the item. You know: ITEM_price or what it was. After a restart, after a quick change, this always happen to me. Is there a way to avoid or fix that?

**Comment by Chessnut** [comment]
I can't replicate.

**Comment by Applad** [comment]
Found something out. If you set it, that you can sell AND buy the same item, the price-change works fine, if you only sell, it doesn't work good.

And something else about it, if I set the price of 9mm ammo to 0, it will be 60. Any way to fix that?

(And by the way, didn't understand how to make the STools for doorsethidden etc.)
