### ISSUE TITLE
[Bug] Can't Drink when Thirsty

### ISSUE THREAD

**Issue by mcderrr** [Chessnut/hl2rp#35]
I'm testing the all the current versions and only using a couple plugins from the NSplugins as well. When my character is thirsty even if I am losing health from how thirsty he is, it stills say "you do not need to consume this right now" Can seem to find out why.

**Comment by JakeyCakey** [comment]
You are using the vanilla foods, they only replenish your stamina. For the cookfood foods you need to have the other catagory foods.
