### ISSUE TITLE
[???] How do I make a combine character?

### ISSUE THREAD

**Issue by stealthiily** [Chessnut/hl2rp#36]
Can someone tell me how to make a combine character for my HL2RP server?

I need to add myself to the Civil Protection class. But how?

**Comment by Connall** [comment]
You need to set yourself as an admin/owner (if owner it can be done by putting nut_setowner <yourname> in the server console when you join)

You will then need to whitelist yourself for the faction /plywhitelist "<name>" "Civil Protection"

Then the option will appear in the menu.

**Comment by stealthiily** [comment]
Thanks.

**Comment by stealthiily** [comment]
BTW, I made a RCT, How do I level it up?

**Comment by Connall** [comment]
By changing the name from RCT to something like DvL, OfC or SeC.

**Comment by NDKilla** [comment]
In addition to the above comment, the default recruit rank is "RCT" the default unit ranks are "05" "04" "03" "02" "01" and "OfC" and the default elite ranks are "EpU' "DvL" and "SeC" I believe.
Setting your name to anything including these should change your model and rank
also, this issue should be closed
