### ISSUE TITLE
Some more Suggestions

### ISSUE THREAD

**Issue by KaiNW** [Chessnut/hl2rp#37]
Add the Ability to set Attributes, would be useful for CP's

Add these Waypoint like things you can see in CW, but not only for Waypoints, even for 2D3D 
Panels/Textpanels, could get useful i think.

Maybe an Interface for Doors? (2D3D) And maybe the State of the door.

A Second, combine-only dispatch?

Ability to fill the ration bags in workcycles?

**Comment by ghost** [comment]
id like an interface for doors to allow co-owners and other things
id like better title systems for doors
like running around the nexus is cool i like /doorsetunownable "Nexus Lobby" but it would be nice if I could change the "Unownable Door" 2ndary text

**Comment by Thadah** [comment]
I heard 2D3D panels in great numbers lag a lot, and since there are a lot of doors in the map, it wouldn't be a really good idea.
And by Waypoints you mean the areas? You can make them with /areaadd

**Comment by KaiNW** [comment]
With waypoints i meanvto Palace Text/panels not only in surfaces i mean like markers and this text/panel is always faces you
