### ISSUE TITLE
[Bug] Voices overlapping

### ISSUE THREAD

**Issue by DevulOLD** [Chessnut/hl2rp#43]
Just watch this and you'll get the idea.
https://a.pomf.se/wcmkgi.mp4

This didn't use to happen.

No errors to display.

To do this yourself, type two voice commands or more as CP.

**Comment by Chessnut** [comment]
This is an issue related to the server. The server is unable to find HL2
sound files so it treats each voice file as if it has 0 length.

**Comment by DevulOLD** [comment]
I'll quickly test on a listen server and call back.

**Comment by DevulOLD** [comment]
Came back, on my listen server (Windows) it works a dream. wtf, why can't my Linux server find these files... I'll do some digging.

**Comment by Chessnut** [comment]
I'm guessing it worked in the listen server?

**Comment by DevulOLD** [comment]
Yeah sorry I edited the post.

**Comment by Chessnut** [comment]
Maybe one solution is just default everyone to 1 second, but the sounds
that are too long or too short wouldn't sound right.

**Comment by DevulOLD** [comment]
I'm really not sure. There is probably a greater solution.

**Comment by Chessnut** [comment]
I'll try asking on Facepunch for a solution.

**Comment by Devul** [comment]
I looked at something on the GMod wiki and found this global func

http://wiki.garrysmod.com/page/Global/SoundDuration

Useful?

**Comment by DevulOLD** [comment]
Possible solution?

Can we rely on the client to get SoundDuration?

![aye](http://i.imgur.com/a03vGlx.png)

**Comment by Chessnut** [comment]
I'll test it right now.
