### ISSUE TITLE
[NutScript 1.1] Strange color sky

### ISSUE THREAD

**Issue by art-gur** [Chessnut/hl2rp#49]
![Screen](http://s1.hostingkartinok.com/uploads/images/2015/03/1f6e4b310aafd4acca39153a6e2db647.jpg)

**Comment by Chessnut** [comment]
Are you using a day/night cycle script?

**Comment by art-gur** [comment]
No, do not use.

**Comment by Chessnut** [comment]
Someone else has reported this on Facepunch: http://facepunch.com/showthread.php?t=1455391

So it may be an issue with the new GMod update. I'm no sure so you can try asking there.

**Comment by art-gur** [comment]
Fine, thanks!

**Comment by art-gur** [comment]
Fixed in Gmod update 16.03.2015
