### ISSUE TITLE
[Bug] Combine locks on the wrong side of the door after a map reload.

### ISSUE THREAD

**Issue by odessadraekavik** [Chessnut/hl2rp#5]
"Some" combine locks are spawning on the wrong side of the door (Rotating doors) after reloading the map / restarting the server.

Exemple : Cells doors on rp_industrial17_v1.

**Comment by Chessnut** [comment]
I think before the locks would spawn at weird angles due to dues loading at certain angles. I'll look into it.

**Comment by ArttuFromHyperia** [comment]
I'll second this, but on rp_c18_v1.

**Comment by Mors-Quaedam** [comment]
This one appears to be fixed now for me with the latest update to NS/HL2RP
