### ISSUE TITLE
[1.1] Placement of Combine Locks on fence doors

### ISSUE THREAD

**Issue by Daishii** [Chessnut/hl2rp#52]
The placement of Combine Locks on fence doors are bugging out. See attached images.

Placing the lock on the door normally:
![rp_industrial17_v10005](https://cloud.githubusercontent.com/assets/11427303/6608509/329ab6c8-c850-11e4-80fb-768b6f1ce4f7.jpg)

Placing the lock on the door normally from the other side:
![rp_industrial17_v10009](https://cloud.githubusercontent.com/assets/11427303/6608513/38954a66-c850-11e4-9f4c-f38c0ce46454.jpg)

Placing the lock on the corner of the door:
![rp_industrial17_v10010](https://cloud.githubusercontent.com/assets/11427303/6608515/39298ec4-c850-11e4-8984-8f86b30748b7.jpg)

**Comment by blt950** [comment]
Same issue here. It seems to effect all func_door_rotating and func_door. prop_door_rotating is all good.

**Comment by blt950** [comment]
This has been fixed now #70
