### ISSUE TITLE
[1.1] Combine are now unable to open blastdoors.

### ISSUE THREAD

**Issue by Daishii** [Chessnut/hl2rp#55]
After applying the recent updates to the schema and framework, the combine-openable doors in rp_industrial17_v1 have stopped opening.

**Comment by Chessnut** [comment]
Which door? I just tested it and it works fine.

**Comment by Daishii** [comment]
I'm having problems with all of them. Interesting, I'll have to try a fresh install.

**Comment by Daishii** [comment]
There must be something wrong on my side. I did a fresh install, deleted everything from the database, the data folder files. Still doesn't work. I'll keep looking

**Comment by Daishii** [comment]
I set-up a brand new server and downloaded NutScript, the HL2RP schema and the Moderator addon and installed them on the server. No files were copied from the old server.

The doors still don't work.

**Comment by blt950** [comment]
I've tested this out myself now, I have the same issue as Daishii.
My combine can open normal doors (prop_door_rotating / func_door_rotating) , but not "combine doors" (func_door)

**Comment by blt950** [comment]
I've tried to debug this a little bit with print() functions through everywhere. What I found is that it detects the press E key in GM:KeyPress, triggers the run of "PlayerUse" hook. 

There it says stop, and I don't get any prints from the GM:PlayerUse().

**Comment by Chessnut** [comment]
PlayerUse does not get called on doors with +use disables flag. That's why
there is the PlayerUseDoor hook.

**Comment by blt950** [comment]
Not sure I understand. So what do I need to do to open combine-doors, which is one of the most essential things in HL2RP?

Because they're supposed to be opened, even though the +USE flag is disabled on them (for a reason, most HL2RP maps have it that way).

**Comment by Chessnut** [comment]
They should already be opening. Which map are you having difficulty on?

**Comment by blt950** [comment]
rp_industrial17_v1
I believe it's the same map as Daishi got problem on, as I've spoken to him.

**Comment by Chessnut** [comment]
https://dl.dropboxusercontent.com/u/24983881/ShareX/2015/03/rp_industrial17_v1%202015-3-15%2010-17-34.webm

?

**Comment by Chessnut** [comment]
Here, try updating now.

**Comment by blt950** [comment]
Uhm nope.. Same thing.

**Comment by Daishii** [comment]
Not working for me either.

**Comment by blt950** [comment]
I fixed the issue. It's not Nutscript or the schema, it was actually a stupid Workshop addon using a hook wrongly, so it overrided the gamemode function. That explains also why SHIFT+E never worked as well.

The addon which was causing this is "Playable Piano".

**Comment by Daishii** [comment]
Alright, that explains it. I never realized that I did have the same workshop collection downloading on the server straight from the command line - therefore a clean install didn't help me.

Problem solved, issue closed.
