### ISSUE TITLE
[1.1] [SUGGESTION] /charsearch command from NS 1.0

### ISSUE THREAD

**Issue by Daishii** [Chessnut/hl2rp#56]
There used to be a command in the NS 1.0 version of HL2RP that allowed a character's inventory to be searched while tied up. I think that would be a great addition to the current version as well.

**Comment by blt950** [comment]
Defiantly needed :+1: 

Should be also binded to like F4 by default or similar.

**Comment by NDKilla** [comment]
I was thinking about trying to code this and might still.. hopefully it becomes a default feature before I add it custom.
@Chessnut: Subject_Alpha/Jake said he was going to give you the code for our /apply function, I wasn't sure if you wanted it default or not.

**Comment by Chessnut** [comment]
Note to self: This is already being worked on but I forgot to commit any changes before I left. Still need to add the permissions for moving items b/t inventories and handle hiding the inventory from the player being searched. Might want to add inventory object to bots in-case human test subject is not available.

**Comment by Chessnut** [comment]
Added in 668c6ee3b03c9628cfd5018e52d6dec005babcb3
