### ISSUE TITLE
[Bug] Data, objectives and vocodes are not working after editing sh_config and sh_civilprotection (Faction file)

### ISSUE THREAD

**Issue by franzhoog** [Chessnut/hl2rp#6]
When I try to edit data and objectives, they simply don't change for me or other characters. Additionally, vocodes don't work for anyone with the Civil Protection Recruit, Elite or Unit classes.

**Comment by Chessnut** [comment]
Sounds like you broke the voice commands.

**Comment by franzhoog** [comment]
I haven't edited them.
