### ISSUE TITLE
Recognizing people

### ISSUE THREAD

**Issue by GlorifiedPig** [Chessnut/hl2rp#65]
I have noticed, nobody can recognize anybody. Everybody is just unknown. How do I make it so they can recognize at talking range?

**Comment by Chessnut** [comment]
Did you press F3?

**Comment by GlorifiedPig** [comment]
@Chessnut I have discovered I am not using the latest version, but /recognize did work, but it does not work as a citizen. Any ideas?

**Comment by blt950** [comment]
Update to the latest version.
