### ISSUE TITLE
Players time out a lot, mostly when using a menu.

### ISSUE THREAD

**Issue by GlorifiedPig** [Chessnut/hl2rp#66]
This isn't very common, but it's not rare. My players randomly time out with no message in the console (for them too, they don't get any errors), and their Garry's Mod crashes sometimes. Any clue?

**Comment by Chessnut** [comment]
What addons/plugins do you have?

**Comment by GlorifiedPig** [comment]
@Chessnut This was doing this before I had any addons or plugins, but this is what I have: Badair, Broadcast, Flashlight, Legs, Machine, MOTD, Notes, Parkour, Quests, Radio, Randomitem, Searching, Thirdperson and Tieing.

**Comment by Chessnut** [comment]
Try having a clean server with only the schema and the framework and see if
that fixes anything.

**Comment by GlorifiedPig** [comment]
@Chessnut It does not work =/

**Comment by Chessnut** [comment]
You deleted all the addons and custom plugins?

**Comment by GlorifiedPig** [comment]
Yes

**Comment by Chessnut** [comment]
I'm not sure then.

**Comment by art-gur** [comment]
I have a server where players come and open the menu, there is a connection error and starts the auto shutdown. In this case, the server does not turn off, and works on it and play the other players.

**Comment by Chessnut** [comment]
Try removing the legs plugin in the nutscript plugins folder and see of
that helps

**Comment by blt950** [comment]
Only the players are timeing out randomly?

If yes, it sounds like they've a connection problem, or maybe they got some clientside addons which messes up something.

**Comment by GlorifiedPig** [comment]
Yea, I never timed out, once, but all of my members time out. @blt950

**Comment by blt950** [comment]
Sounds more like a srcds/network issue than Nutscript you ask me.
If your server is on localhost, it would explain why you don't time out, but others do. 

But well, I suppose rather asking on Facepunch or other places, because it doesn't sound as a Nutscript issue to me.
