### ISSUE TITLE
Gamemode appearing as "NS - Unknown"

### ISSUE THREAD

**Issue by GlorifiedPig** [Chessnut/hl2rp#67]
My gamemode appears as NS - Unknown when I try to join, and it gets stuck on "Initializing Player Data" (I just updated my HL2RP to version 1.1)

**Comment by GlorifiedPig** [comment]
EDIT: I have fixed the issue where it sais "NS - Unknown", but the Initializing Player Data still continues

**Comment by GlorifiedPig** [comment]
EDIT: I have fixed these problems. You may close this

**Comment by blt950** [comment]
Close it yourself.
