### ISSUE TITLE
[Suggestion] New /apply command!

### ISSUE THREAD

**Issue by GlorifiedPig** [Chessnut/hl2rp#69]
Just like in Clockwork, there should be a /apply command where it sais your name then ID. It should be only to the nearest people though

**Comment by blt950** [comment]
/apply is not a part of Clockwork, it's just a plugin to it.

I don't think /apply needs to be implemented as a part of the schema. You can rather make a own plugin for this. My opinion is that /apply is a command for "lazy people", who can't bother to write and remember their CID or name.

**Comment by GlorifiedPig** [comment]
@blt950, It's also used for new people. I haven't had one person who joined my server who actually knows how to play (and I normally get about 10 people on), but I can create it myself.

**Comment by Chessnut** [comment]
I agree with @blt950, if they are just new tell them it's in the description of the card item.

**Comment by blt950** [comment]
As @Chessnut said. If they're new, just tell them how to apply and where you find the details you need to do it. You're not going to learn them that if you make an /apply command.

**Comment by NDKilla** [comment]
For the record I have an apply command somewhere if someone wants it, I do use it on my server, but most of the above are also true.

Pimg @KillingPigs123
