### ISSUE TITLE
[Needed feature] Shoot locks to open doors.

### ISSUE THREAD

**Issue by franzhoog** [Chessnut/hl2rp#7]
Combine need to be able to shoot locks off doors in order to get into them quickly by force.

**Comment by VeXan39231** [comment]
I agree with this, very needed feature!

**Comment by Chessnut** [comment]
What about regular citizens with weapons?

**Comment by franzhoog** [comment]
That would be great too.

**Comment by Applad** [comment]
There is already a plugin about that, but not in Chessnut's plugin collection. It's called "breaching".

**Comment by LLBwithBSc** [comment]
Link anyone to that plugin?

**Comment by Mukhle** [comment]
I know im kinda late but here's a link
https://github.com/Qemist0365/NSPlugins/blob/master/breaching.lua
