### ISSUE TITLE
Nexus doors refuse to open

### ISSUE THREAD

**Issue by gmanc2** [Chessnut/hl2rp#82]
The nexus doors refuse to open for combine and/or any other class a screen shot of the door can be found below.

http://cloud-2.steamusercontent.com/ugc/530638916533436542/FC7FC161C0D0C26715D338BF71813857D0CCDD99/

**Comment by Chessnut** [comment]
Try removing the faction from the door.

**Comment by gmanc2** [comment]
I've already tried that. I'm assuming it's code related because it worked fine on 1.1 and its only nexus doors that do it do you think it could be related to the MetaTable?

**Comment by Chessnut** [comment]
Do you have the piano addon?

**Comment by gmanc2** [comment]
Yes, would that be causing the issue? If so why?

**Comment by Chessnut** [comment]
I'll have to look into it, but someone else had a similar issue. I'm guessing it might be overriding something relating to key presses.

For now you'll just need to remove it.
