### ISSUE TITLE
Major Radio Error

### ISSUE THREAD

**Issue by snwdaaa** [Chessnut/hl2rp#86]
[ERROR] gamemodes/hl2rpanti/plugins/radio/sh_plugin.lua:211: attempt to index a nil value
1. onCanHear - gamemodes/hl2rpanti/plugins/radio/sh_plugin.lua:211
   1. send - gamemodes/nutscript/gamemode/core/libs/sh_chatbox.lua:155
   2. old_hook_call - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:253
      1. Run - lua/includes/modules/momo/compat.lua:30
      2. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
      3. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
      4. unknown - lua/includes/extensions/net.lua:32

When this error occurs, The radio chat is disapperd

**Comment by Chessnut** [comment]
What is the line?

**Comment by stnngfm** [comment]
Line 211, 'onCanHear = function(speaker, listener)'

**Comment by NDKilla** [comment]
I can confirm this happened on my server before (can't check or get logs As I'm out of the country)  I googled the issue and temp fixed it with some code I found online but it appears to be broken last time I checked. The radio appeared to break any time /radio was used and no one could hear it. Then even when people should hear it later the plugin was still broke.

**Comment by NDKilla** [comment]
@Chessnut Thank you! Have been unable to fix this myself forever since I started looking at ChessNut. Can't wait to update later and try it.
