### ISSUE TITLE
[Q] Rank System.

### ISSUE THREAD

**Issue by 7beat** [Chessnut/hl2rp#87]
Hello Cheesnut. I know there's rank system in hl2rp and it's very interesting. Could you explain me how exactly can i rank up in combine or CPs faction? I cant really figure it. Im asking cuz it really fits a stalker rp.

**Comment by Chessnut** [comment]
This isn't the HL2 RP Git page and you change ranks by changing the name.

**Comment by NDKilla** [comment]
@Chessnut this is probably a bad place to leavethis comment, but I'm on my nook, Don't have my phone, And you got me curious.

What do you mean this isn't the hl2rp github? Also.. I had an issue with custom "combine" (they almose copy pasted code but I changed factions)  door locks I made but don't know how to describe it so I'll get back to you on that later

**Comment by Chessnut** [comment]
Oh thought this was NutScript because people usually make that mistake. woops

**Comment by 7beat** [comment]
@Chessnut Huh? I dont get it. So normal player can change his rank by command /charsetname ?!
So all this lua stuff is useless?

**Comment by 7beat** [comment]
Ok thanks for respond
