### ISSUE TITLE
Radio randomly stops working

### ISSUE THREAD

**Issue by strayfromlight** [Chessnut/hl2rp#88]
As the title suggests, the radio command randomly stops and starts working at random. The sound will still trigger to all players who own a radio upon it being used, but no text appears, not even in the console log.

**Comment by Chessnut** [comment]
https://github.com/Chessnut/hl2rp/issues/86
https://github.com/Chessnut/hl2rp/issues/73
https://github.com/Chessnut/hl2rp/issues/62
https://github.com/Chessnut/NutScript/issues/402

?

https://github.com/Chessnut/NutScript/commit/5bb02f25dd382cdb19cc1a871e1a5a0d6a7d32b5

???
