### ISSUE TITLE
[BUG?] Blurry Scanner Photos.

### ISSUE THREAD

**Issue by odessadraekavik** [Chessnut/hl2rp#9]
Hello,

Is it normal that the scanner photos are somewhat "blurry" or "difficult to see" ?

Exemple : http://i.imgur.com/3qgWpCO.jpg

**Comment by VeXan39231** [comment]
It is normal

**Comment by odessadraekavik** [comment]
Ok then, But maybe it could be a less "blurry" in dark areas ? ( I don't know if it's possible, but that would be amazing ), on gm_construct for exemple, it's working perfectly, we can see the photos just fine, but on night time maps, we can barelly see anything :/
