### ISSUE TITLE
Question about items / also website

### ISSUE THREAD

**Issue by NDKilla** [Chessnut/hl2rp#90]
When creating custom items, can you make them purchasable by a class only? (I'm aware ITEM.faction exists and I thought I tried ITEM.class)

Also, the site on your profile (http://chessnut.info) doesn't work. It returns some default Apache file.

**Comment by Thadah** [comment]
I don't know about the first issue, but the NutScript official website is now http://nutscript.rocks

**Comment by NDKilla** [comment]
Thank you for the reply :) I found that in another issue. It was mostly so @Chessnut would update bio
