### ISSUE TITLE
Classes?

### ISSUE THREAD

**Issue by fulltimehobo** [Chessnut/hl2rp#91]
What are classes and how do I give them out to people. 
Also how would I make divisions for OTA

**Comment by NDKilla** [comment]
@fulltimehobo 
All default classes are currently automatically assigned to FACTION_CP members depending on what their name is (what the code defines the 'rank' as)

You can make 'divisions' by renaming OTA and just roleplaying it (like I did)
or you can create a custom class for every division :) 

check the existing code for classes

**Comment by NDKilla** [comment]
As for what classes are.. well.. it's a pretty standard definition. They can do different things depending on what you want. Currently they change permissions for CP's depending on their rank.

**Comment by fulltimehobo** [comment]
So will I need to make a different Faction for each rank
FACTION.name = "fCopName"
FACTION.desc = "fCopDesc"
FACTION.color = Color(25, 30, 180)
FACTION.isDefault = false
FACTION.models = {
    "models/police.mdl"
}
FACTION.weapons = {"nut_stunstick"}
FACTION.pay = 25
FACTION.isGloballyRecognized = true

function FACTION:onGetDefaultName(client)
    if (SCHEMA.digitsLen >= 1) then
        local digits = math.random(tonumber("1"..string.rep("0", SCHEMA.digitsLen-1)), tonumber(string.rep("9", SCHEMA.digitsLen)))
        return SCHEMA.cpPrefix..table.GetFirstValue(SCHEMA.rctRanks).."."..digits, true
    else
        return SCHEMA.cpPrefix..table.GetFirstValue(SCHEMA.rctRanks), true
    end
end

FACTION_CP = FACTION.index

**Comment by fulltimehobo** [comment]
that is my current metrocop

**Comment by fulltimehobo** [comment]
so my cop is set to recruit but how would I get it to elite for example without making a new faction

**Comment by NDKilla** [comment]
You don't need a new faction for each rank

Factions are like teams

Personally I have rct-01 one faction and all commanding units in a "command" faction, but this is just my preference

if you want, you can just use classes

**Comment by NDKilla** [comment]
Create a new CP (that code for the faction sets the default name (which in turn makes it a recruit)

change the name so that "EpU" is somewhere in the name. Class should change.

You could change the way the classes work, but currently they automatically work depending on the name (and what the name must contain is determined by a config setting called eliteRanks or something in schema file

**Comment by fulltimehobo** [comment]
I have made my recruit have access to the scanner class but when I become it the name still stays as recruit

**Comment by NDKilla** [comment]
Because the name used to set the class.. the class doesnt set the name..
if you want to change your name, use the admin command /charsetname ..

**Comment by fulltimehobo** [comment]
could you give me an example of one of your faction and class codes please

**Comment by NDKilla** [comment]
What do you want it to do? I'm currently working on a custom gamemode and I shut down my servers in the meantime.. I don't usually work with classes, but if all your trying to do is change your name, you don't need to worry about the classes.. just use the command.. if you want, you're free to message me and tell me what you'd like to do

**Comment by NDKilla** [comment]
@fulltimehobo https://gitter.im/NDKilla/Chat join if you want
